
export const indianLanguages = [
    { name: 'Assamese', code: 'as' },
    { name: 'Bengali', code: 'bn' },
    { name: 'Bodo', code: 'brx' },
    { name: 'Dogri', code: 'doi' },
    { name: 'English', code: 'en' },
    { name: 'Gujarati', code: 'gu' },
    { name: 'Hindi', code: 'hi' },
    { name: 'Kannada', code: 'kn' },
    { name: 'Kashmiri', code: 'ks' },
    { name: 'Konkani', code: 'gom' },
    { name: 'Maithili', code: 'mai' },
    { name: 'Malayalam', code: 'ml' },
    { name: 'Manipuri', code: 'mni' },
    { name: 'Marathi', code: 'mr' },
    { name: 'Nepali', code: 'ne' },
    { name: 'Odia', code: 'or' },
    { name: 'Punjabi', code: 'pa' },
    { name: 'Sanskrit', code: 'sa' },
    { name: 'Santali', code: 'sat' },
    { name: 'Sindhi', code: 'sd' },
    { name: 'Tamil', code: 'ta' },
    { name: 'Telugu', code: 'te' },
    { name: 'Urdu', code: 'ur' }
];
